# Generated by Django 4.2.28 on 2026-02-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salesrecord_purchaserecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField()),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateTimeField()),
                ('items', models.JSONField(blank=True, default=list)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
