# Generated by Django 4.2.28 on 2026-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dishesovertargetrecord_dashboardkpirecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptrecord',
            name='file_url',
            field=models.TextField(blank=True),
        ),
    ]
