import type { Ingredient, Purchase, Recipe, PosItem, Alert, DashboardKPI, Restaurant } from "./types"

export const mockRestaurant: Restaurant = {
  id: "1",
  name: "Manila Bites Restaurant",
  seatingCapacity: 25,
  region: "NCR",
  city: "Manila",
  cuisine: "Filipino",
  targetFoodCostPercentage: 30,
  targetFoodCostRange: { min: 28, max: 32 },
  categoryTargets: {
    Mains: 30,
    Drinks: 20,
    Desserts: 25,
    Appetizers: 28,
  },
  defaultCurrency: "PHP",
  timezone: "Asia/Manila",
}

export const mockIngredients: Ingredient[] = [
  {
    id: "1",
    name: "Chicken Thigh",
    category: "Meat",
    unit: "kg",
    lastPurchasePrice: 180,
    benchmarkPrice: 165,
    lastPurchasedDate: new Date("2025-11-10"),
    priceTrend: [160, 162, 165, 168, 170, 175, 180, 182, 180, 180],
  },
  {
    id: "2",
    name: "Pork Belly",
    category: "Meat",
    unit: "kg",
    lastPurchasePrice: 220,
    benchmarkPrice: 210,
    lastPurchasedDate: new Date("2025-11-08"),
    priceTrend: [200, 202, 205, 208, 210, 212, 215, 218, 220, 220],
  },
  {
    id: "3",
    name: "Tomato",
    category: "Veg",
    unit: "kg",
    lastPurchasePrice: 45,
    benchmarkPrice: 48,
    lastPurchasedDate: new Date("2025-11-12"),
    priceTrend: [55, 52, 50, 48, 46, 45, 44, 43, 45, 45],
  },
  {
    id: "4",
    name: "Onion",
    category: "Veg",
    unit: "kg",
    lastPurchasePrice: 35,
    benchmarkPrice: 38,
    lastPurchasedDate: new Date("2025-11-11"),
    priceTrend: [40, 39, 38, 37, 36, 35, 35, 35, 35, 35],
  },
  {
    id: "5",
    name: "Garlic",
    category: "Veg",
    unit: "kg",
    lastPurchasePrice: 250,
    benchmarkPrice: 240,
    lastPurchasedDate: new Date("2025-11-09"),
    priceTrend: [200, 210, 220, 230, 240, 245, 250, 250, 250, 250],
  },
  {
    id: "6",
    name: "Rice",
    category: "Dry Goods",
    unit: "kg",
    lastPurchasePrice: 52,
    benchmarkPrice: 50,
    lastPurchasedDate: new Date("2025-11-07"),
    priceTrend: [48, 49, 49, 50, 50, 51, 51, 52, 52, 52],
  },
  {
    id: "7",
    name: "Cooking Oil",
    category: "Dry Goods",
    unit: "L",
    lastPurchasePrice: 85,
    benchmarkPrice: 80,
    lastPurchasedDate: new Date("2025-11-05"),
    priceTrend: [70, 72, 75, 77, 78, 80, 82, 85, 85, 85],
  },
  {
    id: "8",
    name: "Salt",
    category: "Dry Goods",
    unit: "kg",
    lastPurchasePrice: 25,
    benchmarkPrice: 25,
    lastPurchasedDate: new Date("2025-11-10"),
    priceTrend: [25, 25, 25, 25, 25, 25, 25, 25, 25, 25],
  },
]

export const mockPurchases: Purchase[] = [
  {
    id: "1",
    date: new Date("2025-11-12"),
    ingredientId: "1",
    ingredientName: "Chicken Thigh",
    quantity: 5,
    unit: "kg",
    totalPrice: 900,
    unitPrice: 180,
    supplierId: "1",
    supplier: "Golden Poultry",
    type: "Regular",
  },
  {
    id: "2",
    date: new Date("2025-11-11"),
    ingredientId: "2",
    ingredientName: "Pork Belly",
    quantity: 3,
    unit: "kg",
    totalPrice: 660,
    unitPrice: 220,
    supplierId: "2",
    supplier: "Farmer's Direct",
    type: "Regular",
  },
  {
    id: "3",
    date: new Date("2025-11-11"),
    ingredientId: "3",
    ingredientName: "Tomato",
    quantity: 8,
    unit: "kg",
    totalPrice: 360,
    unitPrice: 45,
    supplierId: "3",
    supplier: "Makati Palengke",
    type: "Regular",
  },
]

export const mockPosItems: PosItem[] = [
  { id: "1", name: "Pork Sisig Rice Bowl", category: "Mains", sellingPrice: 250, hasRecipe: true },
  { id: "2", name: "Chicken Adobo Plate", category: "Mains", sellingPrice: 280, hasRecipe: true },
  { id: "3", name: "Sinigang Pork Ribs", category: "Mains", sellingPrice: 290, hasRecipe: true },
  { id: "4", name: "Iced Tea", category: "Drinks", sellingPrice: 45, hasRecipe: false },
  { id: "5", name: "Coffee", category: "Drinks", sellingPrice: 55, hasRecipe: false },
  { id: "6", name: "Leche Flan", category: "Desserts", sellingPrice: 85, hasRecipe: false },
]

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    posItemId: "1",
    posItemName: "Pork Sisig Rice Bowl",
    sellingPrice: 250,
    ingredients: [
      {
        ingredientId: "2",
        ingredientName: "Pork Belly",
        quantityPerPortion: 0.15,
        unit: "kg",
        unitCost: 220,
        costPerPortion: 33,
      },
      {
        ingredientId: "4",
        ingredientName: "Onion",
        quantityPerPortion: 0.05,
        unit: "kg",
        unitCost: 35,
        costPerPortion: 1.75,
      },
      {
        ingredientId: "5",
        ingredientName: "Garlic",
        quantityPerPortion: 0.02,
        unit: "kg",
        unitCost: 250,
        costPerPortion: 5,
      },
      {
        ingredientId: "6",
        ingredientName: "Rice",
        quantityPerPortion: 0.15,
        unit: "kg",
        unitCost: 52,
        costPerPortion: 7.8,
      },
    ],
    totalPlateCost: 47.55,
    foodCostPercentage: 19,
  },
  {
    id: "2",
    posItemId: "2",
    posItemName: "Chicken Adobo Plate",
    sellingPrice: 280,
    ingredients: [
      {
        ingredientId: "1",
        ingredientName: "Chicken Thigh",
        quantityPerPortion: 0.2,
        unit: "kg",
        unitCost: 180,
        costPerPortion: 36,
      },
      {
        ingredientId: "3",
        ingredientName: "Tomato",
        quantityPerPortion: 0.08,
        unit: "kg",
        unitCost: 45,
        costPerPortion: 3.6,
      },
      {
        ingredientId: "4",
        ingredientName: "Onion",
        quantityPerPortion: 0.05,
        unit: "kg",
        unitCost: 35,
        costPerPortion: 1.75,
      },
      {
        ingredientId: "6",
        ingredientName: "Rice",
        quantityPerPortion: 0.15,
        unit: "kg",
        unitCost: 52,
        costPerPortion: 7.8,
      },
    ],
    totalPlateCost: 49.15,
    foodCostPercentage: 17.6,
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "1",
    title: "Chicken Thigh: Price Spike Detected",
    description: "Chicken thigh increased +18% vs last month. Consider updating menu prices or recipe.",
    type: "ingredient",
    severity: "warning",
    date: new Date("2025-11-12"),
    status: "open",
    relatedId: "1",
  },
  {
    id: "2",
    title: "Sisig Bowl Over Target",
    description: "Pork Sisig Rice Bowl at 38% food cost (target 30%).",
    type: "dish",
    severity: "critical",
    date: new Date("2025-11-11"),
    status: "open",
    relatedId: "1",
  },
  {
    id: "3",
    title: "Supplier Overcharging",
    description: "Your sugar price is 25% above NCR supermarket benchmark.",
    type: "supplier",
    severity: "warning",
    date: new Date("2025-11-10"),
    status: "snoozed",
  },
]

export const mockDashboardKPI: DashboardKPI = {
  currentFoodCostPercentage: 31.2,
  targetRange: { min: 28, max: 32 },
  projectedFoodCostPercentage: 33.5,
  projectedChange: 2.3,
  topCostDrivers: [
    { ingredient: "Chicken Thigh", percentage: 28 },
    { ingredient: "Pork Belly", percentage: 24 },
    { ingredient: "Cooking Oil", percentage: 18 },
  ],
  potentialSavings: 12450,
}

export const mockAnalyticsData = [
  { date: "Nov 1", foodCostPercentage: 28.5 },
  { date: "Nov 2", foodCostPercentage: 29.1 },
  { date: "Nov 3", foodCostPercentage: 28.8 },
  { date: "Nov 4", foodCostPercentage: 30.2 },
  { date: "Nov 5", foodCostPercentage: 30.5 },
  { date: "Nov 6", foodCostPercentage: 29.9 },
  { date: "Nov 7", foodCostPercentage: 31.3 },
  { date: "Nov 8", foodCostPercentage: 31.1 },
  { date: "Nov 9", foodCostPercentage: 30.8 },
  { date: "Nov 10", foodCostPercentage: 31.5 },
  { date: "Nov 11", foodCostPercentage: 31.2 },
  { date: "Nov 12", foodCostPercentage: 31.2 },
]

export const mockDishesOverTarget = [
  {
    dish: "Pork Sisig Rice Bowl",
    mainIngredient: "Pork Belly",
    ingredientAmount: "150g",
    ingredientPrice: 220,
    ingredientUnit: "kg",
    foodCostPercentage: 38,
    target: 30,
    variance: 8,
    salesVolume: 45,
    revenueImpact: 360,
  },
  {
    dish: "Sinigang Pork Ribs",
    mainIngredient: "Pork Ribs",
    ingredientAmount: "200g",
    ingredientPrice: 240,
    ingredientUnit: "kg",
    foodCostPercentage: 35,
    target: 30,
    variance: 5,
    salesVolume: 32,
    revenueImpact: 160,
  },
  {
    dish: "Iced Tea",
    mainIngredient: "Tea Leaves",
    ingredientAmount: "10g",
    ingredientPrice: 800,
    ingredientUnit: "kg",
    foodCostPercentage: 28,
    target: 20,
    variance: 8,
    salesVolume: 120,
    revenueImpact: 960,
  },
]
