import type { Ingredient, Purchase, Recipe, PosItem, Alert, DashboardKPI, Restaurant, SalesRecord } from "./types"

export const mockRestaurant: Restaurant = {
  id: "1",
  name: "Manila Bites Restaurant",
  seatingCapacity: 25,
  region: "NCR",
  city: "Manila",
  cuisine: "Filipino",
  targetFoodCostPercentage: 30,
  targetFoodCostRange: { min: 28, max: 32 },
  categoryTargets: {
    Mains: 30,
    Drinks: 20,
    Desserts: 25,
    Appetizers: 28,
  },
  defaultCurrency: "PHP",
  timezone: "Asia/Manila",
  posProvider: "toast",
}

export const mockIngredients: Ingredient[] = [
  {
    id: "1",
    name: "Chicken Thigh",
    category: "Meat",
    unit: "kg",
    lastPurchasePrice: 180,
    benchmarkPrice: 165,
    lastPurchasedDate: new Date("2025-11-10"),
    priceTrend: [160, 162, 165, 168, 170, 175, 180, 182, 180, 180],
    currentStock: 15.5,
  },
  {
    id: "2",
    name: "Pork Belly",
    category: "Meat",
    unit: "kg",
    lastPurchasePrice: 220,
    benchmarkPrice: 210,
    lastPurchasedDate: new Date("2025-11-08"),
    priceTrend: [200, 202, 205, 208, 210, 212, 215, 218, 220, 220],
    currentStock: 8.2,
  },
  {
    id: "3",
    name: "Tomato",
    category: "Veg",
    unit: "kg",
    lastPurchasePrice: 45,
    benchmarkPrice: 48,
    lastPurchasedDate: new Date("2025-11-12"),
    priceTrend: [55, 52, 50, 48, 46, 45, 44, 43, 45, 45],
    currentStock: 12.0,
  },
  {
    id: "4",
    name: "Onion",
    category: "Veg",
    unit: "kg",
    lastPurchasePrice: 35,
    benchmarkPrice: 38,
    lastPurchasedDate: new Date("2025-11-11"),
    priceTrend: [40, 39, 38, 37, 36, 35, 35, 35, 35, 35],
    currentStock: 18.5,
  },
  {
    id: "5",
    name: "Garlic",
    category: "Veg",
    unit: "kg",
    lastPurchasePrice: 250,
    benchmarkPrice: 240,
    lastPurchasedDate: new Date("2025-11-09"),
    priceTrend: [200, 210, 220, 230, 240, 245, 250, 250, 250, 250],
    currentStock: 3.2,
  },
  {
    id: "6",
    name: "Rice",
    category: "Dry Goods",
    unit: "kg",
    lastPurchasePrice: 52,
    benchmarkPrice: 50,
    lastPurchasedDate: new Date("2025-11-07"),
    priceTrend: [48, 49, 49, 50, 50, 51, 51, 52, 52, 52],
    currentStock: 50.0,
  },
  {
    id: "7",
    name: "Cooking Oil",
    category: "Dry Goods",
    unit: "L",
    lastPurchasePrice: 85,
    benchmarkPrice: 80,
    lastPurchasedDate: new Date("2025-11-05"),
    priceTrend: [70, 72, 75, 77, 78, 80, 82, 85, 85, 85],
    currentStock: 25.0,
  },
  {
    id: "8",
    name: "Salt",
    category: "Dry Goods",
    unit: "kg",
    lastPurchasePrice: 25,
    benchmarkPrice: 25,
    lastPurchasedDate: new Date("2025-11-10"),
    priceTrend: [25, 25, 25, 25, 25, 25, 25, 25, 25, 25],
    currentStock: 10.0,
  },
]

export const mockPurchases: Purchase[] = [
  {
    id: "1",
    date: new Date("2025-11-12"),
    ingredientId: "1",
    ingredientName: "Chicken Thigh",
    quantity: 5,
    unit: "kg",
    totalPrice: 900,
    unitPrice: 180,
    supplierId: "1",
    supplier: "Golden Poultry",
    type: "Regular",
  },
  {
    id: "2",
    date: new Date("2025-11-11"),
    ingredientId: "2",
    ingredientName: "Pork Belly",
    quantity: 3,
    unit: "kg",
    totalPrice: 660,
    unitPrice: 220,
    supplierId: "2",
    supplier: "Farmer's Direct",
    type: "Regular",
  },
  {
    id: "3",
    date: new Date("2025-11-11"),
    ingredientId: "3",
    ingredientName: "Tomato",
    quantity: 8,
    unit: "kg",
    totalPrice: 360,
    unitPrice: 45,
    supplierId: "3",
    supplier: "Makati Palengke",
    type: "Regular",
  },
]

export const mockPosItems: PosItem[] = [
  { id: "1", name: "Pork Sisig Rice Bowl", category: "Mains", sellingPrice: 250, hasRecipe: true },
  { id: "2", name: "Chicken Adobo Plate", category: "Mains", sellingPrice: 280, hasRecipe: true },
  { id: "3", name: "Sinigang Pork Ribs", category: "Mains", sellingPrice: 290, hasRecipe: true },
  { id: "4", name: "Iced Tea", category: "Drinks", sellingPrice: 45, hasRecipe: false },
  { id: "5", name: "Coffee", category: "Drinks", sellingPrice: 55, hasRecipe: false },
  { id: "6", name: "Leche Flan", category: "Desserts", sellingPrice: 85, hasRecipe: false },
]

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    posItemId: "1",
    posItemName: "Pork Sisig Rice Bowl",
    sellingPrice: 250,
    ingredients: [
      {
        ingredientId: "2",
        ingredientName: "Pork Belly",
        quantityPerPortion: 0.15,
        unit: "kg",
        totalCost: 33, // 0.15kg costs 33 pesos total
        costPerUnit: 220, // 33 / 0.15 = 220 pesos/kg
        costPerPortion: 33,
      },
      {
        ingredientId: "4",
        ingredientName: "Onion",
        quantityPerPortion: 0.05,
        unit: "kg",
        totalCost: 1.75,
        costPerUnit: 35,
        costPerPortion: 1.75,
      },
      {
        ingredientId: "5",
        ingredientName: "Garlic",
        quantityPerPortion: 0.02,
        unit: "kg",
        totalCost: 5,
        costPerUnit: 250,
        costPerPortion: 5,
      },
      {
        ingredientId: "6",
        ingredientName: "Rice",
        quantityPerPortion: 0.15,
        unit: "kg",
        totalCost: 7.8,
        costPerUnit: 52,
        costPerPortion: 7.8,
      },
    ],
    totalPlateCost: 47.55,
    foodCostPercentage: 19,
  },
  {
    id: "2",
    posItemId: "2",
    posItemName: "Chicken Adobo Plate",
    sellingPrice: 280,
    ingredients: [
      {
        ingredientId: "1",
        ingredientName: "Chicken Thigh",
        quantityPerPortion: 0.2,
        unit: "kg",
        totalCost: 36,
        costPerUnit: 180,
        costPerPortion: 36,
      },
      {
        ingredientId: "3",
        ingredientName: "Tomato",
        quantityPerPortion: 0.08,
        unit: "kg",
        totalCost: 3.6,
        costPerUnit: 45,
        costPerPortion: 3.6,
      },
      {
        ingredientId: "4",
        ingredientName: "Onion",
        quantityPerPortion: 0.05,
        unit: "kg",
        totalCost: 1.75,
        costPerUnit: 35,
        costPerPortion: 1.75,
      },
      {
        ingredientId: "6",
        ingredientName: "Rice",
        quantityPerPortion: 0.15,
        unit: "kg",
        totalCost: 7.8,
        costPerUnit: 52,
        costPerPortion: 7.8,
      },
    ],
    totalPlateCost: 49.15,
    foodCostPercentage: 17.6,
  },
]

const recentDate = (offsetDays: number) => {
  const base = new Date()
  const next = new Date(base)
  next.setDate(base.getDate() - offsetDays)
  return next
}

export const mockSalesRecords: SalesRecord[] = [
  {
    id: "sale_1",
    posItemId: "1",
    posItemName: "Pork Sisig Rice Bowl",
    date: recentDate(2),
    quantity: 32,
  },
  {
    id: "sale_2",
    posItemId: "2",
    posItemName: "Chicken Adobo Plate",
    date: recentDate(1),
    quantity: 28,
  },
  {
    id: "sale_3",
    posItemId: "4",
    posItemName: "Iced Tea",
    date: recentDate(0),
    quantity: 90,
  },
]

export const seedRestaurant: Restaurant = {
  id: "mcd_1",
  name: "MCDO",
  seatingCapacity: 60,
  region: "NCR",
  city: "Manila",
  cuisine: "Fast Casual",
  targetFoodCostPercentage: 30,
  targetFoodCostRange: { min: 28, max: 32 },
  categoryTargets: {
    Mains: 30,
    Drinks: 18,
    Desserts: 22,
    Sides: 28,
  },
  defaultCurrency: "PHP",
  timezone: "Asia/Manila",
  posProvider: "square",
}

export const seedIngredients: Ingredient[] = [
  ...mockIngredients,
  {
    id: "9",
    name: "Potato",
    category: "Veg",
    unit: "kg",
    lastPurchasePrice: 60,
    benchmarkPrice: 58,
    lastPurchasedDate: new Date("2025-11-10"),
    priceTrend: [55, 56, 56, 57, 58, 59, 60, 60, 60, 60],
    currentStock: 22.5,
  },
  {
    id: "10",
    name: "Tea Concentrate",
    category: "Beverages",
    unit: "L",
    lastPurchasePrice: 120,
    benchmarkPrice: 115,
    lastPurchasedDate: new Date("2025-11-11"),
    priceTrend: [110, 112, 112, 113, 114, 115, 118, 120, 120, 120],
    currentStock: 18,
  },
  {
    id: "11",
    name: "Sugar",
    category: "Dry Goods",
    unit: "kg",
    lastPurchasePrice: 70,
    benchmarkPrice: 68,
    lastPurchasedDate: new Date("2025-11-12"),
    priceTrend: [65, 66, 66, 67, 68, 69, 70, 70, 70, 70],
    currentStock: 35,
  },
]

export const seedPosItems: PosItem[] = [
  { id: "m1", name: "Chicken Burger", category: "Mains", sellingPrice: 120, hasRecipe: true },
  { id: "m2", name: "Spaghetti Bowl", category: "Mains", sellingPrice: 95, hasRecipe: true },
  { id: "m3", name: "Fries", category: "Sides", sellingPrice: 55, hasRecipe: true },
  { id: "m4", name: "Iced Tea", category: "Drinks", sellingPrice: 35, hasRecipe: true },
]

export const seedRecipes: Recipe[] = [
  {
    id: "r1",
    posItemId: "m1",
    posItemName: "Chicken Burger",
    sellingPrice: 120,
    ingredients: [
      {
        ingredientId: "1",
        ingredientName: "Chicken Thigh",
        quantityPerPortion: 0.2,
        unit: "kg",
        totalCost: 36,
        costPerUnit: 180,
        costPerPortion: 36,
      },
      {
        ingredientId: "5",
        ingredientName: "Garlic",
        quantityPerPortion: 0.01,
        unit: "kg",
        totalCost: 2.5,
        costPerUnit: 250,
        costPerPortion: 2.5,
      },
      {
        ingredientId: "7",
        ingredientName: "Cooking Oil",
        quantityPerPortion: 0.02,
        unit: "L",
        totalCost: 1.7,
        costPerUnit: 85,
        costPerPortion: 1.7,
      },
    ],
    totalPlateCost: 40.2,
    foodCostPercentage: 34,
  },
  {
    id: "r2",
    posItemId: "m2",
    posItemName: "Spaghetti Bowl",
    sellingPrice: 95,
    ingredients: [
      {
        ingredientId: "3",
        ingredientName: "Tomato",
        quantityPerPortion: 0.2,
        unit: "kg",
        totalCost: 9,
        costPerUnit: 45,
        costPerPortion: 9,
      },
      {
        ingredientId: "4",
        ingredientName: "Onion",
        quantityPerPortion: 0.05,
        unit: "kg",
        totalCost: 1.75,
        costPerUnit: 35,
        costPerPortion: 1.75,
      },
      {
        ingredientId: "5",
        ingredientName: "Garlic",
        quantityPerPortion: 0.02,
        unit: "kg",
        totalCost: 5,
        costPerUnit: 250,
        costPerPortion: 5,
      },
      {
        ingredientId: "7",
        ingredientName: "Cooking Oil",
        quantityPerPortion: 0.01,
        unit: "L",
        totalCost: 0.85,
        costPerUnit: 85,
        costPerPortion: 0.85,
      },
    ],
    totalPlateCost: 16.6,
    foodCostPercentage: 17,
  },
  {
    id: "r3",
    posItemId: "m3",
    posItemName: "Fries",
    sellingPrice: 55,
    ingredients: [
      {
        ingredientId: "9",
        ingredientName: "Potato",
        quantityPerPortion: 0.25,
        unit: "kg",
        totalCost: 15,
        costPerUnit: 60,
        costPerPortion: 15,
      },
      {
        ingredientId: "7",
        ingredientName: "Cooking Oil",
        quantityPerPortion: 0.03,
        unit: "L",
        totalCost: 2.55,
        costPerUnit: 85,
        costPerPortion: 2.55,
      },
      {
        ingredientId: "8",
        ingredientName: "Salt",
        quantityPerPortion: 0.01,
        unit: "kg",
        totalCost: 0.25,
        costPerUnit: 25,
        costPerPortion: 0.25,
      },
    ],
    totalPlateCost: 17.8,
    foodCostPercentage: 32,
  },
  {
    id: "r4",
    posItemId: "m4",
    posItemName: "Iced Tea",
    sellingPrice: 35,
    ingredients: [
      {
        ingredientId: "10",
        ingredientName: "Tea Concentrate",
        quantityPerPortion: 0.03,
        unit: "L",
        totalCost: 3.6,
        costPerUnit: 120,
        costPerPortion: 3.6,
      },
      {
        ingredientId: "11",
        ingredientName: "Sugar",
        quantityPerPortion: 0.02,
        unit: "kg",
        totalCost: 1.4,
        costPerUnit: 70,
        costPerPortion: 1.4,
      },
    ],
    totalPlateCost: 5,
    foodCostPercentage: 14,
  },
]

export const seedPurchases: Purchase[] = [
  ...mockPurchases,
  {
    id: "4",
    date: new Date("2026-02-06"),
    ingredientId: "9",
    ingredientName: "Potato",
    quantity: 10,
    unit: "kg",
    totalPrice: 600,
    unitPrice: 60,
    supplierId: "4",
    supplier: "Fresh Harvest",
    type: "Regular",
  },
  {
    id: "5",
    date: new Date("2026-02-10"),
    ingredientId: "10",
    ingredientName: "Tea Concentrate",
    quantity: 5,
    unit: "L",
    totalPrice: 600,
    unitPrice: 120,
    supplierId: "5",
    supplier: "Brew Supply",
    type: "Regular",
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "1",
    title: "Chicken Thigh: Price Spike Detected",
    description: "Chicken thigh increased +18% vs last month. Consider updating menu prices or recipe.",
    type: "ingredient",
    severity: "warning",
    date: new Date("2025-11-12"),
    status: "open",
    relatedId: "1",
  },
  {
    id: "2",
    title: "Sisig Bowl Over Target",
    description: "Pork Sisig Rice Bowl at 38% food cost (target 30%).",
    type: "dish",
    severity: "critical",
    date: new Date("2025-11-11"),
    status: "open",
    relatedId: "1",
  },
  {
    id: "3",
    title: "Supplier Overcharging",
    description: "Your sugar price is 25% above NCR supermarket benchmark.",
    type: "supplier",
    severity: "warning",
    date: new Date("2025-11-10"),
    status: "snoozed",
  },
]

export const mockDashboardKPI: DashboardKPI = {
  currentFoodCostPercentage: 31.2,
  targetRange: { min: 28, max: 32 },
  projectedFoodCostPercentage: 33.5,
  projectedChange: 2.3,
  topCostDrivers: [
    { ingredient: "Chicken Thigh", percentage: 28 },
    { ingredient: "Pork Belly", percentage: 24 },
    { ingredient: "Cooking Oil", percentage: 18 },
  ],
  potentialSavings: 12450,
}

export const mockAnalyticsData = [
  { date: "Nov 1", foodCostPercentage: 28.5 },
  { date: "Nov 2", foodCostPercentage: 29.1 },
  { date: "Nov 3", foodCostPercentage: 28.8 },
  { date: "Nov 4", foodCostPercentage: 30.2 },
  { date: "Nov 5", foodCostPercentage: 30.5 },
  { date: "Nov 6", foodCostPercentage: 29.9 },
  { date: "Nov 7", foodCostPercentage: 31.3 },
  { date: "Nov 8", foodCostPercentage: 31.1 },
  { date: "Nov 9", foodCostPercentage: 30.8 },
  { date: "Nov 10", foodCostPercentage: 31.5 },
  { date: "Nov 11", foodCostPercentage: 31.2 },
  { date: "Nov 12", foodCostPercentage: 31.2 },
]

export const mockDishesOverTarget = [
  {
    dish: "Pork Sisig Rice Bowl",
    mainIngredient: "Pork Belly",
    ingredientAmount: "150g",
    ingredientPrice: 220,
    ingredientUnit: "kg",
    foodCostPercentage: 38,
    target: 30,
    variance: 8,
    salesVolume: 45,
    revenueImpact: 360,
  },
  {
    dish: "Sinigang Pork Ribs",
    mainIngredient: "Pork Ribs",
    ingredientAmount: "200g",
    ingredientPrice: 240,
    ingredientUnit: "kg",
    foodCostPercentage: 35,
    target: 30,
    variance: 5,
    salesVolume: 32,
    revenueImpact: 160,
  },
  {
    dish: "Iced Tea",
    mainIngredient: "Tea Leaves",
    ingredientAmount: "10g",
    ingredientPrice: 800,
    ingredientUnit: "kg",
    foodCostPercentage: 28,
    target: 20,
    variance: 8,
    salesVolume: 120,
    revenueImpact: 960,
  },
]

export const seedSalesRecords: SalesRecord[] = [
  {
    id: "m_sale_1",
    posItemId: "m1",
    posItemName: "Chicken Burger",
    date: new Date("2026-02-05"),
    quantity: 96,
  },
  {
    id: "m_sale_2",
    posItemId: "m2",
    posItemName: "Spaghetti Bowl",
    date: new Date("2026-02-05"),
    quantity: 88,
  },
  {
    id: "m_sale_3",
    posItemId: "m3",
    posItemName: "Fries",
    date: new Date("2026-02-05"),
    quantity: 160,
  },
  {
    id: "m_sale_4",
    posItemId: "m4",
    posItemName: "Iced Tea",
    date: new Date("2026-02-05"),
    quantity: 190,
  },
  {
    id: "m_sale_5",
    posItemId: "m1",
    posItemName: "Chicken Burger",
    date: new Date("2026-02-08"),
    quantity: 120,
  },
  {
    id: "m_sale_6",
    posItemId: "m3",
    posItemName: "Fries",
    date: new Date("2026-02-08"),
    quantity: 210,
  },
  {
    id: "m_sale_7",
    posItemId: "m2",
    posItemName: "Spaghetti Bowl",
    date: new Date("2026-02-09"),
    quantity: 92,
  },
  {
    id: "m_sale_8",
    posItemId: "m4",
    posItemName: "Iced Tea",
    date: new Date("2026-02-09"),
    quantity: 240,
  },
  {
    id: "m_sale_9",
    posItemId: "m1",
    posItemName: "Chicken Burger",
    date: new Date("2026-02-11"),
    quantity: 104,
  },
  {
    id: "m_sale_10",
    posItemId: "m2",
    posItemName: "Spaghetti Bowl",
    date: new Date("2026-02-11"),
    quantity: 78,
  },
]

export const seedDashboardKPI = mockDashboardKPI
export const seedAnalyticsData = mockAnalyticsData
export const seedDishesOverTarget = mockDishesOverTarget
export const seedAlerts = mockAlerts
